# This code works as a comfyui node to save an image by an exact filename
# typed-in manually or generated by previous string handling nodes. 
# Usage: put this file into the custom_nodes dir and restart comfyui
# Version 2026.0703.1
# Copyright © 2026 <github.com/zhangdoujohndoe>
# Licence: see https://mit-license.org

import os
import json
import numpy as np
from PIL import Image
from PIL.PngImagePlugin import PngInfo
import folder_paths

class SaveImageExact:
    def __init__(self):
        self.output_dir = folder_paths.get_output_directory()
        # "output" type is required for ComfyUI's frontend to know where to fetch the preview from
        self.type = "output"

    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "images": ("IMAGE",),
                "filename": ("STRING", {"default": "Comfy.png"}),
                "embed_workflow": ("BOOLEAN", {"default": True}),
            },
            "hidden": {
                "prompt": "PROMPT",
                "extra_pnginfo": "EXTRA_PNGINFO"
            }
        }

    RETURN_TYPES = ()
    FUNCTION = "save_images"
    OUTPUT_NODE = True
    CATEGORY = "image"

    def save_images(self, images, filename, embed_workflow, prompt=None, extra_pnginfo=None):
        results = list()
        
        # Determine paths and automatically create any missing nested folders (e.g. "my_folder/Comfy.png")
        full_path = os.path.join(self.output_dir, filename)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        
        # Split subfolder and file name for the UI preview dictionary
        subfolder, file = os.path.split(filename)

        for image in images:
            # Convert ComfyUI tensor back to standard PIL image
            i = 255. * image.cpu().numpy()
            img = Image.fromarray(np.clip(i, 0, 255).astype(np.uint8))
            
            # Handle Workflow Metadata
            metadata = None
            if embed_workflow and filename.lower().endswith(".png"):
                metadata = PngInfo()
                if prompt is not None:
                    metadata.add_text("prompt", json.dumps(prompt))
                if extra_pnginfo is not None:
                    for x in extra_pnginfo:
                        metadata.add_text(x, json.dumps(extra_pnginfo[x]))

            # Save exactly matching your input filename string
            # (compress_level=4 is ComfyUI's standard for optimized PNG saving)
            img.save(full_path, pnginfo=metadata, compress_level=4)
            
            # Append image information to trigger the UI preview
            results.append({
                "filename": file,
                "subfolder": subfolder,
                "type": self.type
            })
            
        # Returning {"ui": {"images": ...}} tells the ComfyUI web UI to display these images
        return {"ui": {"images": results}}

NODE_CLASS_MAPPINGS = {"SaveImageExact": SaveImageExact}
NODE_DISPLAY_NAME_MAPPINGS = {"SaveImageExact": "Save Image Exact (No Counter)"}
